(()=>{"use strict";
const answers={};let current=0,gameTimer=null,seconds=30,audioOn=true,ctx=null;
const pages=[...document.querySelectorAll(".page")],bar=document.getElementById("progressBar"),progressText=document.getElementById("progressText");
function sound(freq=520){if(!audioOn)return;try{ctx ||= new(window.AudioContext||window.webkitAudioContext)();if(ctx.state==="suspended")ctx.resume();const o=ctx.createOscillator(),g=ctx.createGain();o.type="sine";o.frequency.value=freq;g.gain.setValueAtTime(.035,ctx.currentTime);g.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+.18);o.connect(g);g.connect(ctx.destination);o.start();o.stop(ctx.currentTime+.19)}catch(e){}}
function go(n){clearInterval(gameTimer);pages.forEach(p=>p.classList.toggle("active",Number(p.dataset.page)===n));current=n;bar.style.width=(n*10)+"%";progressText.textContent=n===0?"البداية":`المرحلة ${n} من 10`;window.scrollTo({top:0,behavior:"smooth"});sound(n===10?760:430);if(n===7)startGame();if(n===10)summary()}
document.querySelectorAll("[data-next]").forEach(b=>b.addEventListener("click",()=>go(Number(b.dataset.next))));
document.querySelectorAll(".choice").forEach(b=>b.addEventListener("click",()=>{const p=b.closest(".page");p.querySelectorAll(".choice").forEach(x=>x.classList.remove("selected"));b.classList.add("selected");answers[p.dataset.page]=b.dataset.answer;const f=p.querySelector(".feedback");if(f)f.textContent="تم الاختيار 💗";sound(590);const r=b.getBoundingClientRect();for(let i=0;i<5;i++){const x=document.createElement("span");x.className="floating";x.textContent="♥";x.style.left=(r.left+r.width/2+(Math.random()-.5)*60)+"px";x.style.fontSize=(12+Math.random()*10)+"px";x.style.animationDuration=(1.2+Math.random())+"s";document.body.appendChild(x);setTimeout(()=>x.remove(),2400)}}));
function startGame(){const grid=document.getElementById("heartGrid"),msg=document.getElementById("gameMsg"),next=document.getElementById("gameNext"),timer=document.getElementById("timer");grid.replaceChildren();next.classList.add("hidden");seconds=30;timer.textContent="00:30";msg.textContent="القلب المختلف مخبّى بين القلوب...";const target=Math.floor(Math.random()*25);for(let i=0;i<25;i++){const b=document.createElement("button");b.className="game-heart";b.type="button";b.textContent=i===target?"💖":"💗";b.addEventListener("click",()=>{if(i===target){clearInterval(gameTimer);msg.textContent="لقيتيه! 🫣❤";next.classList.remove("hidden");sound(780)}else{b.animate([{transform:"translateX(-4px)"},{transform:"translateX(4px)"},{transform:"none"}],{duration:180});sound(220)}});grid.appendChild(b)}gameTimer=setInterval(()=>{seconds--;timer.textContent="00:"+String(Math.max(0,seconds)).padStart(2,"0");if(seconds<=0){clearInterval(gameTimer);msg.textContent="خلص الوقت! ارجعي للمرحلة السابقة ثم عودي للمحاولة 💗"}},1000)}
document.getElementById("saveDate").addEventListener("click",()=>{const d=document.getElementById("date").value,t=document.getElementById("time").value;if(!d||!t){document.getElementById("dateError").textContent="اختاري التاريخ والوقت أولاً 🫣";return}answers.date=d;answers.time=t;go(10)});
function summary(){let d="غير محدد";if(answers.date){const date=new Date(answers.date+"T00:00:00");d=date.toLocaleDateString("ar-SY",{year:"numeric",month:"long",day:"numeric"})}document.getElementById("summary").innerHTML="<b>المكان:</b> "+(answers[4]||"لم يتم الاختيار")+"<br><b>الأكلة:</b> "+(answers[5]||"لم يتم الاختيار")+"<br><b>أجمل ذكرى:</b> "+(answers[8]||"لم يتم الاختيار")+"<br><b>الموعد:</b> "+d+" — "+(answers.time||"غير محدد");for(let i=0;i<28;i++){const x=document.createElement("span");x.className="floating";x.textContent=i%3?"❤":"✦";x.style.left=Math.random()*100+"vw";x.style.animationDuration=(1.3+Math.random()*1.8)+"s";document.body.appendChild(x);setTimeout(()=>x.remove(),3400)}}
document.getElementById("soundBtn").addEventListener("click",()=>{audioOn=!audioOn;document.getElementById("soundBtn").textContent=audioOn?"🔊":"🔇";if(audioOn)sound()});
document.getElementById("restart").addEventListener("click",()=>{Object.keys(answers).forEach(k=>delete answers[k]);document.querySelectorAll(".choice").forEach(b=>b.classList.remove("selected"));document.getElementById("date").value="";document.getElementById("time").value="";document.getElementById("dateError").textContent="";go(0)});
setInterval(()=>{if(document.hidden)return;const h=document.createElement("span");h.className="floating";h.textContent=Math.random()>.3?"♥":"✦";h.style.left=Math.random()*100+"vw";h.style.fontSize=(10+Math.random()*12)+"px";h.style.animationDuration=(7+Math.random()*5)+"s";document.body.appendChild(h);setTimeout(()=>h.remove(),13000)},1200);
go(0);
})();