let selectedPlace="",selectedFood="",selectedMemory="",chosenDate="",chosenTime="",finalNoCount=0,soundOn=true,audioCtx=null,gameTimer=null,timeLeft=30;
const screens=[...document.querySelectorAll(".screen")],progress=document.getElementById("progressBar"),toast=document.getElementById("toast");
function go(n){screens.forEach(s=>s.classList.toggle("active",+s.dataset.screen===n));progress.style.width=n/10*100+"%";window.scrollTo({top:0,behavior:"smooth"});playTone(n===10?"win":"click");if(n===7)startGame();if(n===10){renderSummary();celebrate()}}
function msg(t){toast.textContent=t;toast.classList.add("show");setTimeout(()=>toast.classList.remove("show"),2200)}
function pickPlace(btn,name){document.querySelectorAll(".place").forEach(x=>x.classList.remove("selected"));btn.classList.add("selected");selectedPlace=name;document.getElementById("placeResult").textContent="تم اختيار المكان 💗";msg("اختيار جميل 🫣❤️");playTone("select")}
function pickFood(btn,name){document.querySelectorAll(".food").forEach(x=>x.classList.remove("selected"));btn.classList.add("selected");selectedFood=name;document.getElementById("foodResult").textContent="تم اختيار الأكلة 😋❤️";document.getElementById("next5").classList.remove("hidden");playTone("select")}
function pickMemory(btn,name){document.querySelectorAll(".memory").forEach(x=>x.classList.remove("selected"));btn.classList.add("selected");selectedMemory=name;document.getElementById("memoryResult").textContent="هاي الذكرى صارت محفوظة بالقصة 📸💗";document.getElementById("next8").classList.remove("hidden");burst(btn);playTone("select")}
function saveDate(){let d=document.getElementById("date").value,t=document.getElementById("time").value;if(!d||!t){msg("اختاري التاريخ والوقت أولًا 🌸");return}let dt=new Date(d+"T"+t);chosenDate=new Intl.DateTimeFormat("ar-SY",{weekday:"long",day:"numeric",month:"long",year:"numeric"}).format(dt);chosenTime=new Intl.DateTimeFormat("ar-SY",{hour:"numeric",minute:"2-digit"}).format(dt);msg("تم حفظ الموعد ❤️");go(10)}
function renderSummary(){document.getElementById("summary").innerHTML="📍 المكان: "+(selectedPlace||"لم يتم تحديده")+"<br>🍽️ الأكل: "+(selectedFood||"لم يتم تحديده")+"<br>📸 أجمل ذكرى: "+(selectedMemory||"كل الأيام ذكريات جميلة 🫣")+"<br>📅 الموعد: "+(chosenDate||"لم يتم تحديده")+"<br>🕐 الوقت: "+(chosenTime||"لم يتم تحديده")}
function startGame(){clearInterval(gameTimer);timeLeft=30;document.getElementById("timer").textContent="00:30";document.getElementById("gameResult").textContent="القلب المختلف مخبّى بين القلوب...";document.getElementById("next7").classList.add("hidden");let grid=document.getElementById("heartGrid");grid.innerHTML="";let correct=Math.floor(Math.random()*16);for(let i=0;i<16;i++){let b=document.createElement("button");b.className="heart-cell";b.textContent=i===correct?"💖":"💗";b.onclick=()=>{if(i===correct){clearInterval(gameTimer);document.getElementById("gameResult").textContent="لقيتيه! كنتِ مركزة 😂❤️";document.getElementById("next7").classList.remove("hidden");[...grid.children].forEach(x=>x.disabled=true);burst(b);celebrate();playTone("win")}else{msg("مو هاد 😏 جربي قلب ثاني");playTone("wrong")}};grid.appendChild(b)}gameTimer=setInterval(()=>{timeLeft--;document.getElementById("timer").textContent="00:"+String(timeLeft).padStart(2,"0");if(timeLeft<=0){clearInterval(gameTimer);document.getElementById("gameResult").textContent="خلص الوقت 😭 جربي مرة ثانية!"}},1000)}
function toggleSound(){soundOn=!soundOn;document.getElementById("soundToggle").textContent=soundOn?"🔊":"🔇";if(soundOn)playTone("click")}
function ensureAudio(){if(!audioCtx)audioCtx=new(window.AudioContext||window.webkitAudioContext)();if(audioCtx.state==="suspended")audioCtx.resume()}
function playTone(kind){if(!soundOn)return;try{ensureAudio();let o=audioCtx.createOscillator(),g=audioCtx.createGain(),now=audioCtx.currentTime,f=kind==="win"?660:kind==="select"?520:kind==="wrong"?180:420;o.type="sine";o.frequency.setValueAtTime(f,now);o.frequency.exponentialRampToValueAtTime(f*1.35,now+.16);g.gain.setValueAtTime(.0001,now);g.gain.exponentialRampToValueAtTime(.055,now+.015);g.gain.exponentialRampToValueAtTime(.0001,now+.28);o.connect(g).connect(audioCtx.destination);o.start(now);o.stop(now+.3);if(kind==="win"){setTimeout(()=>playTone("select"),130);setTimeout(()=>playTone("click"),260)}}catch(e){}}
function burst(el){let r=el.getBoundingClientRect();for(let i=0;i<8;i++){let h=document.createElement("div");h.className="particle burst";h.textContent="❤";h.style.left=r.left+r.width/2+(Math.random()-.5)*70+"px";h.style.top=r.top+"px";h.style.fontSize=10+Math.random()*14+"px";h.style.animationDuration=.8+Math.random()*.8+"s";document.body.appendChild(h);setTimeout(()=>h.remove(),1800)}}
function celebrate(){for(let i=0;i<30;i++)setTimeout(()=>{let p=document.createElement("div");p.className="particle";p.textContent=["❤️","🌸","✨","💕"][Math.floor(Math.random()*4)];p.style.left=Math.random()*100+"vw";p.style.fontSize=12+Math.random()*22+"px";p.style.animationDuration=4+Math.random()*4+"s";document.getElementById("particles").appendChild(p);setTimeout(()=>p.remove(),9000)},i*70)}
setInterval(()=>{let p=document.createElement("div");p.className="particle";p.textContent=Math.random()>.5?"♡":"♥";p.style.left=Math.random()*100+"vw";p.style.fontSize=12+Math.random()*18+"px";p.style.animationDuration=6+Math.random()*5+"s";document.getElementById("particles").appendChild(p);setTimeout(()=>p.remove(),12000)},900)
document.addEventListener("click",()=>{if(soundOn)ensureAudio()},{once:true});
